Repository kSideProject/kpring, pull requests merged in 2024-04, with the labels that each got.

#2 chore : 모듈 구성 버그 픽스
  README.md
  auth/gradlew
  auth/gradlew.bat
  auth/settings.gradle.kts
  build.gradle.kts
  chat/gradlew
  chat/gradlew.bat
  chat/settings.gradle.kts
  core/gradlew
  core/gradlew.bat
  core/settings.gradle.kts
  server/gradlew
  server/gradlew.bat
  server/settings.gradle.kts
  settings.gradle.kts
  src/main/kotlin/com/sideproject/kping/KpingApplication.kt
  src/main/resources/application.properties
  src/test/kotlin/com/sideproject/kping/KpingApplicationTests.kt
  user/gradlew
  user/gradlew.bat
  user/settings.gradle.kts
Labels: bug

#8 [Auth] 토큰 생성 API 구현 : POST /api/v1/token
  auth/build.gradle.kts
  auth/src/main/kotlin/kpring/auth/api/error/ErrorApi.kt
  auth/src/main/kotlin/kpring/auth/api/v1/AuthController.kt
  auth/src/main/kotlin/kpring/auth/service/TokenService.kt
  auth/src/main/resources/application.properties
  auth/src/main/resources/application.yaml
  auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
  auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
  core/build.gradle.kts
  core/src/main/kotlin/kpring/core/CoreApplication.kt
  core/src/main/kotlin/kpring/core/auth/dto/request/CreateTokenRequest.kt
  core/src/main/kotlin/kpring/core/auth/dto/response/CreateTokenResponse.kt
  core/src/main/kotlin/kpring/core/auth/enums/TokenType.kt
Labels: enhancement

#11 [Test] 테스트 모듈 생성 및 Spring Rest Doc DSL 구현
  settings.gradle.kts
  test/build.gradle.kts
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBodyBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocHeaderBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocRequestBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocResponseBuilder.kt
Labels: enhancement

#12 bug : snippet 없을 때, 에러 발생
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
Labels: bug

#18 Spring Rest docs를 통한 OpenApi3 문서 생성 자동화
  test/build.gradle.kts
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
Labels: enhancement

#19 인증서버 4xx, 5xx API 응답 테스트 작성 및 버그 수정
  auth/src/main/kotlin/kpring/auth/api/error/ErrorApi.kt
  auth/src/main/kotlin/kpring/auth/exception/TokenExpiredException.kt
  auth/src/main/kotlin/kpring/auth/service/TokenService.kt
  auth/src/main/kotlin/kpring/auth/util/JwtUtil.kt
  auth/src/test/kotlin/kpring/auth/AuthApplicationTests.kt
  auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
  auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
Labels: bug, enhancement

#20 [User] 친구추가 기능구현
  user/build.gradle.kts
  user/docs/친구추가 기능요구사항 README.md
  user/docs/친구추가 기능요구사항 체크리스트.md
  user/src/main/kotlin/kpring/user/controller/UserAddController.kt
  user/src/main/kotlin/kpring/user/dto/request/FriendsRequestDto.kt
  user/src/main/kotlin/kpring/user/dto/result/FriendsResultDto.kt
  user/src/main/kotlin/kpring/user/entity/User.kt
  user/src/main/kotlin/kpring/user/repository/UserRepository.kt
  user/src/main/kotlin/kpring/user/service/UserAddService.kt
  user/src/main/kotlin/kpring/user/service/UserAddServiceImpl.kt
  user/src/test/kotlin/kpring/user/controller/UserAddControllerTest.kt
  user/src/test/kotlin/kpring/user/service/UserAddServiceImplTest.kt
Labels: enhancement

#24 [TEST] MockMvc Spring REST docs 커스텀 DSL 확장
  test/build.gradle.kts
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocPathParamBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocQueryParamBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocRequestBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocResponseBuilder.kt
Labels: enhancement

#25 feat : user 모듈 클래스 생성
  .gitignore
  user/build.gradle.kts
  user/src/main/kotlin/kpring/user/controller/FriendController.kt
  user/src/main/kotlin/kpring/user/controller/LoginController.kt
  user/src/main/kotlin/kpring/user/controller/UserAddController.kt
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/dto/request/CreateUserRequest.java
  user/src/main/kotlin/kpring/user/dto/request/FriendsAddRequestDto.kt
  user/src/main/kotlin/kpring/user/dto/request/FriendsRequestDto.kt
  user/src/main/kotlin/kpring/user/dto/request/LoginRequest.java
  user/src/main/kotlin/kpring/user/dto/request/UpdateUserProfileRequest.java
  user/src/main/kotlin/kpring/user/dto/result/CreateUserResponse.java
  user/src/main/kotlin/kpring/user/dto/result/DeleteFriendResponse.java
  user/src/main/kotlin/kpring/user/dto/result/FriendsAddResultDto.kt
  user/src/main/kotlin/kpring/user/dto/result/FriendsResultDto.kt
  user/src/main/kotlin/kpring/user/dto/result/GetFriendsResponse.java
  user/src/main/kotlin/kpring/user/dto/result/GetUserProfileResponse.java
  user/src/main/kotlin/kpring/user/dto/result/LoginResponse.java
  user/src/main/kotlin/kpring/user/dto/result/UpdateUserProfileResponse.java
  user/src/main/kotlin/kpring/user/repository/UserRepository.kt
  user/src/main/kotlin/kpring/user/service/FriendService.java
  user/src/main/kotlin/kpring/user/service/LoginService.java
  user/src/main/kotlin/kpring/user/service/UserAddService.kt
  user/src/main/kotlin/kpring/user/service/UserAddServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserService.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/test/kotlin/kpring/user/controller/UserAddControllerTest.kt
  user/src/test/kotlin/kpring/user/service/UserAddServiceImplTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: duplicate

#27 fix : mockMvc dsl 연동 버그
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
Labels: bug

#33 [user] 회원정보 수정 API 실패 테스트
  user/src/main/kotlin/kpring/user/controller/ExceptionController.java
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/dto/result/FailMessageResponse.java
  user/src/main/kotlin/kpring/user/dto/result/UpdateUserProfileResponse.java
  user/src/main/kotlin/kpring/user/exception/ErrorCode.java
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: Test

#36 [Auth] validation API 스펙 변경
  auth/src/main/kotlin/kpring/auth/api/v1/AuthController.kt
  auth/src/main/kotlin/kpring/auth/service/TokenService.kt
  auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
  auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
  core/src/main/kotlin/kpring/core/auth/dto/request/TokenValidationRequest.kt
  core/src/main/kotlin/kpring/core/auth/dto/response/TokenValidationResponse.kt
Labels: Fix

#35 [USER] 회원 탈퇴 API 테스트 케이스 작성
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: Test

#34 [USER] 회원 조회 API 테스트 케이스 작성
  core/src/main/kotlin/kpring/core/auth/client/AuthClient.java
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/dto/result/GetUserProfileResponse.java
  user/src/main/kotlin/kpring/user/exception/ErrorCode.java
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: Test

#37 [Chat] Feat/create chat
  chat/build.gradle.kts
  chat/src/main/kotlin/kpring/chat/api/v1/ChatController.kt
  chat/src/main/kotlin/kpring/chat/config/ClientConfig.java
  chat/src/main/kotlin/kpring/chat/exception/ErrorCode.kt
  chat/src/main/kotlin/kpring/chat/exception/GlobalException.kt
  chat/src/main/kotlin/kpring/chat/exception/GlobalExceptionHandler.kt
  chat/src/main/kotlin/kpring/chat/model/Chat.kt
  chat/src/main/kotlin/kpring/chat/repository/ChatRepository.kt
  chat/src/main/kotlin/kpring/chat/service/ChatService.kt
  chat/src/main/resources/application.properties
  chat/src/main/resources/application.yml
  core/src/main/kotlin/kpring/core/chat/dto/request/CreateChatRequest.kt
  core/src/main/kotlin/kpring/core/chat/dto/response/CreateChatResponse.kt
  core/src/main/kotlin/kpring/core/global/dto/response/ApiResponse.kt
Labels: enhancement

#39 [Root] gradle 빌드 실패 오류 수정
  build.gradle.kts
  core/build.gradle.kts
  core/src/main/kotlin/kpring/core/auth/client/AuthClient.java
  core/src/main/kotlin/kpring/core/auth/client/AuthClient.kt
  core/src/test/kotlin/kpring/core/CoreApplicationTests.kt
  settings.gradle.kts
  test/build.gradle.kts
  user/build.gradle.kts
  user/src/main/java/kpring/user/controller/ExceptionController.java
  user/src/main/java/kpring/user/dto/request/CreateUserRequest.java
  user/src/main/java/kpring/user/dto/request/LoginRequest.java
  user/src/main/java/kpring/user/dto/request/LogoutRequest.java
  user/src/main/java/kpring/user/dto/request/UpdateUserProfileRequest.java
  user/src/main/java/kpring/user/dto/response/CreateUserResponse.java
  user/src/main/java/kpring/user/dto/response/DeleteFriendResponse.java
  user/src/main/java/kpring/user/dto/response/FailMessageResponse.java
  user/src/main/java/kpring/user/dto/response/GetFriendsResponse.java
  user/src/main/java/kpring/user/dto/response/GetUserProfileResponse.java
  user/src/main/java/kpring/user/dto/response/LoginResponse.java
  user/src/main/java/kpring/user/dto/response/UpdateUserProfileResponse.java
  user/src/main/java/kpring/user/exception/ErrorCode.java
  user/src/main/java/kpring/user/exception/ExceptionWrapper.java
  user/src/main/java/kpring/user/service/FriendService.java
  user/src/main/java/kpring/user/service/LoginService.java
  user/src/main/kotlin/kpring/user/config/ClientConfig.java
  user/src/main/kotlin/kpring/user/config/ClientConfig.kt
  user/src/main/kotlin/kpring/user/controller/FriendController.kt
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/service/UserService.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: bug

#41 fix : ClientConfig convert to kotlin file
  chat/src/main/kotlin/kpring/chat/config/ClientConfig.java
  chat/src/main/kotlin/kpring/chat/config/ClientConfig.kt
Labels: bug

#45 [Infra] k8s on local 에서 auth service 배포 구축
  auth/build.gradle.kts
  auth/src/main/resources/application.yaml
  infra/dev/.helmignore
  infra/dev/Chart.yaml
  infra/dev/compose.yml
  infra/dev/readme.md
  infra/dev/templates/NOTES.txt
  infra/dev/templates/_helpers.tpl
  infra/dev/templates/auth-configmap.yaml
  infra/dev/templates/auth-deployment.yaml
  infra/dev/templates/auth-service.yaml
  infra/dev/templates/deployment.yaml
  infra/dev/templates/ingress.yaml
  infra/dev/templates/redis-deployment.yaml
  infra/dev/templates/redis-service.yaml
  infra/dev/templates/service.yaml
  infra/dev/templates/serviceaccount.yaml
  infra/dev/templates/tests/test-connection.yaml
  infra/dev/values.yaml
Labels: environment

#47 [Infra] 로컬상에서 Auth API 조회 서비스(swagger) 구축
  auth/build.gradle.kts
  auth/src/main/kotlin/kpring/auth/config/StaticResourceConfig.kt
  auth/src/main/resources/application.yaml
  infra/dev/templates/auth-service.yaml
  infra/dev/templates/auth/auth-configmap.yaml
  infra/dev/templates/auth/auth-deployment.yaml
  infra/dev/templates/auth/auth-service.yaml
  infra/dev/templates/auth/redis-deployment.yaml
  infra/dev/templates/auth/redis-service.yaml
  infra/dev/templates/profile-config.yaml
  infra/dev/templates/swagger/deployment.yaml
  infra/dev/templates/swagger/service.yaml
  infra/dev/values.yaml
Labels: environment

#48 [Infra] subchart로 서비스 차트 분할
  infra/.helmignore
  infra/Chart.yaml
  infra/charts/auth/.helmignore
  infra/charts/auth/Chart.yaml
  infra/charts/auth/templates/_helpers.tpl
  infra/charts/auth/templates/auth-configmap.yaml
  infra/charts/auth/templates/auth-deployment.yaml
  infra/charts/auth/templates/auth-service.yaml
  infra/charts/auth/templates/redis-deployment.yaml
  infra/charts/auth/templates/redis-service.yaml
  infra/charts/auth/templates/tests/test-connection.yaml
  infra/charts/auth/values.yaml
  infra/charts/swagger/.helmignore
  infra/charts/swagger/Chart.yaml
  infra/charts/swagger/templates/_helpers.tpl
  infra/charts/swagger/templates/deployment.yaml
  infra/charts/swagger/templates/service.yaml
  infra/charts/swagger/templates/tests/test-connection.yaml
  infra/charts/swagger/values.yaml
  infra/compose.yml
  infra/dev/templates/NOTES.txt
  infra/dev/templates/auth/auth-configmap.yaml
  infra/dev/templates/auth/auth-service.yaml
  infra/dev/templates/deployment.yaml
  infra/dev/templates/ingress.yaml
  infra/dev/templates/service.yaml
  infra/dev/templates/serviceaccount.yaml
  infra/dev/templates/swagger/deployment.yaml
  infra/dev/templates/swagger/service.yaml
  infra/dev/templates/tests/test-connection.yaml
  infra/dev/values.yaml
  infra/readme.md
  infra/templates/_helpers.tpl
  infra/templates/profile-config.yaml
  infra/values.yaml
Labels: environment

#50 [Infra] local profile Swagger Cors 허용
  auth/src/main/kotlin/kpring/auth/AuthApplication.kt
  core/build.gradle.kts
  core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
  core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
  user/src/main/kotlin/kpring/user/UserApplication.kt
Labels: environment

#46 [Chat] ChatRoom 생성 기능 구현
  chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
  chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
  chat/src/main/kotlin/kpring/chat/chat/repository/ChatRepository.kt
  chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
  chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
  chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
  chat/src/main/kotlin/kpring/chat/chatroom/repository/ChatRoomRepository.kt
  chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
  chat/src/main/kotlin/kpring/chat/exception/ErrorCode.kt
  chat/src/main/kotlin/kpring/chat/global/config/ClientConfig.kt
  chat/src/main/kotlin/kpring/chat/global/exception/ErrorCode.kt
  chat/src/main/kotlin/kpring/chat/global/exception/GlobalException.kt
  chat/src/main/kotlin/kpring/chat/global/exception/GlobalExceptionHandler.kt
  core/src/main/kotlin/kpring/core/chat/chat/dto/request/CreateChatRequest.kt
  core/src/main/kotlin/kpring/core/chat/chat/dto/response/CreateChatResponse.kt
  core/src/main/kotlin/kpring/core/chat/chatroom/client/ChatRoomClient.kt
  core/src/main/kotlin/kpring/core/chat/chatroom/dto/request/CreateChatRoomRequest.kt
Labels: enhancement
