Repository kSideProject/kpring, pull requests merged in 2024-07, with the labels that each got.

#204 Feat/auth 로그인 페이지의 alert를 Mui Alert로 변경과 토큰 검증 및 갱신 자동화
  front/src/App.tsx
  front/src/api/axiosInstance.ts
  front/src/api/token.ts
  front/src/components/Auth/LoginBox.tsx
  front/src/index.tsx
  front/src/store/useLoginStore.ts
  front/src/utils/axiosInterceptor.ts
Labels: UI/UX

#212 Feat/auth 토큰이 유효할 경우, 로그인페이지와 회원가입페이지 접근시 메인으로 리디렉션됨
  front/src/App.tsx
  front/src/api/token.ts
  front/src/components/Auth/AuthLayout.tsx
Labels: UI/UX

#213 [Feat] 시그널링 서버 및 프론트엔드 배포 파일 작성
  front/.gitignore
  front/Dockerfile
  front/nginx/nginx.conf
  front/package.json
  front/server/signalingServer.ts
  front/src/components/VideoCall/VideoCallBoxList.tsx
  front/src/components/VideoCall/VideoCallBoxListItem.tsx
  front/src/types/server.ts
  front/yarn.lock
Labels: enhancement, environment

#214 [Feat/auth] 로그인 페이지 비밀번호 보이기/감추기, 로딩 인디케이터, 환경변수 설정
  front/.gitignore
  front/src/api/axiosInstance.ts
  front/src/components/Auth/AuthLayout.tsx
  front/src/components/Auth/JoinBox.tsx
  front/src/components/Auth/LoginBox.tsx
  front/src/hooks/FetchServer.ts
  front/src/hooks/UpdatedServer.ts
Labels: Auth, UI/UX
