Repository kSideProject/kpring, pull requests merged in 2024-12, with the labels that each got.

#313 fix: 수정된 네이밍 컨벤션 반영
  chat/src/main/resources/application.yml
Labels: bug

#317 fix: user module의 application.yaml에 server url 추가
  user/src/main/resources/application.yaml
Labels: bug

#318 [Infra] dev 브랜치 main 으로 병합
  user/src/main/resources/application.yaml
Labels: environment

#320 [Chore] CORS 이슈 해결을 위한 프론트엔드 코드 전달
  front/src/components/Layout/components/rightSidebar/components/messages/NewFriendsList.tsx
  front/src/setupProxy.js
Labels: help wanted

#321 [Fix] User 모듈에 CORS 설정 추가하여 로컬 프론트엔드 요청 허용
  core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
  core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
  user/src/main/kotlin/kpring/user/config/SecurityConfig.kt
Labels: enhancement

#322 [Infra] dev 브랜치를 main 브랜치로 병합
  core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
  core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
  front/src/components/Layout/FriendsRightSideBar.tsx
  front/src/components/Layout/MemberListItem.tsx
  front/src/components/Layout/MessageRightSideBar.tsx
  front/src/components/Layout/ServerInfoSidebar.tsx
  user/src/main/kotlin/kpring/user/config/SecurityConfig.kt
Labels: environment

#323 [CI/CD] 원할한 배포를 위한 Github Actions Workflow 수정 및 변경
  .github/workflows/ci/auth.yml
  .github/workflows/ci/front.yml
  .github/workflows/ci/server.yml
  .github/workflows/ci/user.yml
Labels: environment

#326 workflow 구성 파일 에러 수정
  .github/workflows/ci_auth.yml
  .github/workflows/ci_front.yml
  .github/workflows/ci_server.yml
  .github/workflows/ci_user.yml
Labels: bug

#328 [Fix] 프론트 배포 RUN BUILD 오류 수정
  front/Dockerfile
  front/src/App.tsx
  front/src/components/Layout/components/leftSidebar/components/AddServer.tsx
  front/src/components/Phaser/ServerMap.tsx
  front/src/components/Server/ServerMapWithTheme.tsx
  front/src/components/user/components/UserProfile.tsx
  front/src/pages/Home.tsx
  front/src/pages/Join.tsx
  front/src/pages/Login.tsx
Labels: environment
