Repository kSideProject/kpring, pull requests merged in 2024-05, with the labels that each got.

#55 [User] 회원가입 기능 구현
  user/build.gradle.kts
  user/src/main/java/kpring/user/dto/request/CreateUserRequest.java
  user/src/main/java/kpring/user/dto/response/CreateUserResponse.java
  user/src/main/java/kpring/user/exception/ErrorCode.java
  user/src/main/kotlin/kpring/user/UserApplication.kt
  user/src/main/kotlin/kpring/user/config/WebSecurityConfig.kt
  user/src/main/kotlin/kpring/user/entity/User.kt
  user/src/main/kotlin/kpring/user/repository/UserRepository.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserValidationService.kt
  user/src/main/resources/application.yaml
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: enhancement, API

#53 [WebRTC] **미완성** 초기 구현
  server/build.gradle.kts
  server/src/main/kotlin/kpring/server/config/WebSocketConfiguration.kt
  server/src/main/kotlin/kpring/server/persistence/SignalingController.kt
  server/src/main/resources/static/index.html
  server/src/main/resources/static/peerConfig.js
Labels: enhancement

#59 [Chat] queryDsl mongo 설정 및 셈플 코드 작성
  build.gradle.kts
  chat/build.gradle.kts
  chat/compose.yml
  chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
  chat/src/main/kotlin/kpring/chat/chat/repository/ChatRepository.kt
  chat/src/test/kotlin/kpring/chat/example/SampleTest.kt
Labels: enhancement

#54 [Chat] 채팅방별 채팅 조회 기능 구현
  chat/build.gradle.kts
  chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
  chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
  chat/src/main/kotlin/kpring/chat/chat/repository/ChatRepository.kt
  chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
  chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
  chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
  chat/src/main/kotlin/kpring/chat/chatroom/repository/ChatRoomRepository.kt
  chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
  chat/src/main/kotlin/kpring/chat/global/exception/ErrorCode.kt
  chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
  chat/src/main/resources/application.yml
  chat/src/test/kotlin/kpring/chat/chat/ChatServiceTest.kt
  chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
  chat/src/test/kotlin/kpring/chat/global/ChatRoomTest.kt
  chat/src/test/kotlin/kpring/chat/global/ChatTest.kt
  chat/src/test/kotlin/kpring/chat/global/CommonTest.kt
  core/src/main/kotlin/kpring/core/chat/chat/dto/request/CreateChatRequest.kt
  core/src/main/kotlin/kpring/core/chat/chat/dto/response/ChatResponse.kt
Labels: enhancement, API

#64 [Test] auth test 실행시 redis가 없으면 테스트가 실패하는 오류 수정
  auth/build.gradle.kts
  auth/src/test/kotlin/kpring/auth/repository/ExpireTokenRepositoryTest.kt
  test/build.gradle.kts
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
  test/src/main/kotlin/kpring/test/testcontainer/ContainerContextInitializer.kt
  test/src/main/kotlin/kpring/test/testcontainer/SpringTestContext.kt
Labels: enhancement, Fix

#68 [Auth] auth test 수정
  auth/src/main/kotlin/kpring/auth/util/JwtUtil.kt
  auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
Labels: bug

#57 [User] 회원가입 테스트 코드 작성
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
  user/src/test/kotlin/kpring/user/dto/request/CreateUserRequestTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: Test

#74 [Auth] auth 토큰 검증 api 수정
  auth/src/main/kotlin/kpring/auth/api/error/ErrorApi.kt
  auth/src/main/kotlin/kpring/auth/api/v1/AuthController.kt
  auth/src/main/kotlin/kpring/auth/api/v2/AuthController.kt
  auth/src/main/kotlin/kpring/auth/error/AuthErrorCode.kt
  auth/src/main/kotlin/kpring/auth/error/TokenExpiredException.kt
  auth/src/main/kotlin/kpring/auth/service/TokenService.kt
  auth/src/main/kotlin/kpring/auth/util/JwtUtil.kt
  auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
  auth/src/test/kotlin/kpring/auth/service/TokenServiceTest.kt
  chat/src/test/kotlin/kpring/chat/example/SampleTest.kt
  core/src/main/kotlin/kpring/core/auth/client/AuthClient.kt
  core/src/main/kotlin/kpring/core/auth/dto/response/TokenInfo.kt
  core/src/main/kotlin/kpring/core/global/dto/response/ApiResponse.kt
  core/src/main/kotlin/kpring/core/global/dto/response/ErrorResponse.kt
  core/src/main/kotlin/kpring/core/global/exception/CommonErrorCode.kt
  core/src/main/kotlin/kpring/core/global/exception/ErrorCode.kt
  core/src/main/kotlin/kpring/core/global/exception/ServiceException.kt
  test/src/main/kotlin/kpring/test/testcontainer/SpringTestContext.kt
Labels: Fix

#63 [Chat] 채팅방 나가기 API 구현 : PATCH/api/v1/chatroom
  chat/build.gradle.kts
  chat/src/main/kotlin/kpring/chat/NoArg.kt
  chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
  chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
  chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
  chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
  chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
  chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
  chat/src/main/resources/application.yml
Labels: API, environment

#79 Feat/login
  user/src/main/java/kpring/user/dto/request/LoginRequest.java
  user/src/main/java/kpring/user/exception/ErrorCode.java
  user/src/main/java/kpring/user/service/LoginService.java
  user/src/main/kotlin/kpring/user/config/SecurityConfig.kt
  user/src/main/kotlin/kpring/user/repository/UserRepository.kt
  user/src/main/kotlin/kpring/user/service/LoginService.kt
  user/src/main/kotlin/kpring/user/service/LoginServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserValidationService.kt
  user/src/main/resources/application.yaml
  user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: enhancement, API

#83 [Chat] 채팅방 나가기 테스트코드 작성
  chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
  chat/src/test/kotlin/kpring/chat/chatroom/ChatRoomServiceTest.kt
Labels: enhancement, Chat

#85 [User] UserErrorCode 적용
  user/src/main/java/kpring/user/controller/ExceptionController.java
  user/src/main/java/kpring/user/exception/ErrorCode.java
  user/src/main/java/kpring/user/exception/ExceptionWrapper.java
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/exception/ExceptionController.kt
  user/src/main/kotlin/kpring/user/exception/UserErrorCode.kt
  user/src/main/kotlin/kpring/user/service/LoginServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserValidationService.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: User

#82 [Server] 서버 유저 추가 기능 구현
  core/src/main/kotlin/kpring/core/global/controller/ServiceExceptionRestController.kt
  core/src/main/kotlin/kpring/core/server/dto/request/AddUserAtServerRequest.kt
  server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerUserEntity.kt
  server/src/main/kotlin/kpring/server/application/port/input/AddUserAtServerUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/output/UpdateServerPort.kt
  server/src/main/kotlin/kpring/server/application/service/ServerService.kt
  server/src/main/kotlin/kpring/server/config/CoreConfiguration.kt
  server/src/main/kotlin/kpring/server/domain/Server.kt
  server/src/main/kotlin/kpring/server/domain/ServerUser.kt
  server/src/main/kotlin/kpring/server/error/ServerErrorCode.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImplTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerTest.kt
Labels: enhancement, Server

#95 [Github Actions] Cache Gradle dependencies 추가
  .github/workflows/pr-test.yml
Labels: environment

#96 [User] ApiResponse 적용
  user/src/main/kotlin/kpring/user/controller/FriendController.kt
  user/src/main/kotlin/kpring/user/controller/LoginController.kt
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: enhancement, User

#94 [Auth] auth client 설정 추가
  core/build.gradle.kts
  core/src/main/kotlin/kpring/core/auth/config/AuthClientConfig.kt
  core/src/main/kotlin/kpring/core/global/controller/ServiceExceptionRestController.kt
  core/src/main/kotlin/kpring/core/global/exception/CommonErrorCode.kt
  core/src/main/kotlin/kpring/core/global/exception/DetailErrorCode.kt
  core/src/main/kotlin/kpring/core/global/exception/HttpClientErrorHandle.kt
  core/src/main/kotlin/kpring/core/server/dto/request/CreateServerRequest.kt
  core/src/test/kotlin/kpring/core/global/exception/HttpClientErrorHandleTest.kt
  test/build.gradle.kts
Labels: enhancement, Auth

#93 [Server] 서버 생성 API 테스트 추가
  server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/GetServerPortTest.kt
Labels: Test, Server

#101 [User] 회원가입시 비밀번호 확인 로직 삭제
  user/src/main/java/kpring/user/dto/request/CreateUserRequest.java
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/main/kotlin/kpring/user/service/UserValidationService.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
  user/src/test/kotlin/kpring/user/dto/request/CreateUserRequestTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: API, User

#97 [Github Actions] Build Gradle Cache 적용 및 actions version 업그레이드
  .github/workflows/pr-test.yml
  settings.gradle.kts
Labels: environment

#109 Feat/auth 테마 코드 이동, autocomplete Warning 해결, 회원가입 유효성 검사 추가
  front/src/components/Auth/JoinBox.tsx
  front/src/components/Auth/LoginBox.tsx
  front/src/components/Layout/Layout.tsx
  front/src/hooks/JoinValidation.ts
  front/src/pages/Join.tsx
  front/src/pages/Login.tsx
  front/src/theme/themeConfig.ts
  front/src/types/join.ts
Labels: UI/UX

#105 [Server] 서버 목록 조회 기능 구현
  core/src/main/kotlin/kpring/core/server/dto/ServerSimpleInfo.kt
  server/build.gradle.kts
  server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerUserEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/repository/ServerRepository.kt
  server/src/main/kotlin/kpring/server/application/port/input/AddUserAtServerUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/input/GetServerInfoUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/output/GetServerPort.kt
  server/src/main/kotlin/kpring/server/application/port/output/UpdateServerPort.kt
  server/src/main/kotlin/kpring/server/application/service/ServerService.kt
  server/src/main/kotlin/kpring/server/config/CoreConfiguration.kt
  server/src/main/kotlin/kpring/server/domain/Server.kt
  server/src/main/kotlin/kpring/server/domain/ServerUser.kt
  server/src/main/kotlin/kpring/server/error/ServerErrorCode.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImplTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/GetServerPortTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerTest.kt
Labels: enhancement, Server

#102 [Server] 서버 권한 기능
  core/src/main/kotlin/kpring/core/global/exception/CommonErrorCode.kt
  server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt
  server/src/main/kotlin/kpring/server/application/port/input/AddUserAtServerUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/input/CreateServerUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/output/SaveServerPort.kt
  server/src/main/kotlin/kpring/server/application/service/ServerService.kt
  server/src/main/kotlin/kpring/server/domain/Server.kt
  server/src/main/kotlin/kpring/server/domain/ServerAuthority.kt
  server/src/main/kotlin/kpring/server/domain/ServerRole.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/application/port/input/AddUserAtServerUseCaseTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/SaveServerPortTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerRoleTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerTest.kt
Labels: enhancement, Server

#110 Feat/phaser
  front/src/App.tsx
  front/src/components/Phaser/PhaserGame.tsx
  front/src/components/Phaser/ServerScene.tsx
  front/src/components/Phaser/main.tsx
  front/src/components/Phaser/serverScene/MainServer.ts
  front/src/types/server.ts
Labels: UI/UX

#115 [Infra] user 서비스 db 환경 구성
  infra/charts/user/templates/deployment.yaml
  infra/charts/user/templates/mysql-deployment.yaml
  infra/charts/user/templates/mysql-service.yaml
  infra/charts/user/values.yaml
  user/src/main/resources/application.yaml
Labels: environment

#114 Feat/phaser: Map관련 변수와 함수 이름변경
  front/public/assets/basic_character.png
  front/src/App.tsx
  front/src/components/Phaser/ServerMap.tsx
  front/src/components/Phaser/ServerScene.tsx
  front/src/components/Phaser/main.tsx
  front/src/components/Phaser/serverScene/MainMap.ts
  front/src/components/Phaser/serverScene/Preloader.ts
  front/src/types/server.ts
Labels: UI/UX

#99 [User] 사용자 프로필 조회 API 구현
  user/src/main/java/kpring/user/dto/response/GetUserProfileResponse.java
  user/src/main/kotlin/kpring/user/controller/UserController.kt
  user/src/main/kotlin/kpring/user/service/UserServiceImpl.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
  user/src/test/kotlin/kpring/user/service/UserServiceImplTest.kt
Labels: enhancement, API, User

#116 [Feat/home] 홈페이지에 carousel과 card 컴포넌트 추가
  front/src/components/Home/ServerCard.tsx
  front/src/components/Layout/Header.tsx
  front/src/components/Layout/Layout.tsx
  front/src/components/Layout/LeftSideBar.tsx
  front/src/components/Layout/ServerInfoSidebar.tsx
  front/src/pages/Home.tsx
Labels: question, UI/UX

#119 [Server] 서버 목록 조회시 즐겨찾기 상태 조회 기능 추가
  core/src/main/kotlin/kpring/core/server/dto/ServerSimpleInfo.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/UpdateServerPortMongoImpl.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerProfileEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/entity/ServerUserEntity.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/repository/ServerProfileRepository.kt
  server/src/main/kotlin/kpring/server/application/port/output/GetServerProfilePort.kt
  server/src/main/kotlin/kpring/server/application/port/output/UpdateServerPort.kt
  server/src/main/kotlin/kpring/server/application/service/ServerService.kt
  server/src/main/kotlin/kpring/server/domain/Server.kt
  server/src/main/kotlin/kpring/server/domain/ServerProfile.kt
  server/src/main/kotlin/kpring/server/domain/ServerRole.kt
  server/src/main/resources/application.yml
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/application/port/input/AddUserAtServerUseCaseTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/GetServerPortTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/SaveServerPortTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/UpdateServerPortTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerProfileTest.kt
  server/src/test/kotlin/kpring/server/domain/ServerTest.kt
Labels: enhancement, Server

#129 feat : request part 문서화 DSL 확장 추가
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocMultipartBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocRequestBuilder.kt
Labels: enhancement

#124 Feat/auth 회원가입 페이지의 실시간 유효성 검사 적용
  front/src/components/Auth/JoinBox.tsx
  front/src/hooks/JoinValidation.ts
  front/src/types/join.ts
Labels: UI/UX

#131 [Server] 서버 목록 조회 검색 조건 기능 추가
  core/src/main/kotlin/kpring/core/server/dto/request/GetServerCondition.kt
  server/src/main/kotlin/kpring/server/adapter/input/rest/RestApiServerController.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
  server/src/main/kotlin/kpring/server/application/port/input/GetServerInfoUseCase.kt
  server/src/main/kotlin/kpring/server/application/port/output/GetServerProfilePort.kt
  server/src/main/kotlin/kpring/server/application/service/ServerService.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  server/src/test/kotlin/kpring/server/application/port/output/GetServerProfilePortTest.kt
  test/src/main/kotlin/kpring/test/web/URLBuilder.kt
  test/src/test/kotlin/test/web/URLBuilderTest.kt
Labels: enhancement, Server

#133 [Test] request part object 문서화를 위한 custom dsl 기능 추가
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocMultipartFieldBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocRequestBuilder.kt
Labels: enhancement

#130 [Feat/favorite] 즐겨찾기 기능 및 캐릭터 키보드로 조정
  front/public/assets/basic_character.png
  front/public/assets/character.json
  front/public/assets/character.png
  front/src/components/Home/FavoriteStar.tsx
  front/src/components/Home/ServerCard.tsx
  front/src/components/Home/ServerCardList.tsx
  front/src/components/Layout/ServerInfoSidebar.tsx
  front/src/components/Phaser/serverScene/MainMap.ts
  front/src/components/Phaser/serverScene/Preloader.ts
  front/src/hooks/FavoriteServer.ts
  front/src/pages/Home.tsx
  front/src/stores/store.ts
  front/src/utils/fakeData.ts
Labels: UI/UX

#136 [Core&Test] jib 빌드 에러 수정
  auth/src/test/kotlin/kpring/auth/api/AuthControllerTest.kt
  core/build.gradle.kts
  core/src/main/kotlin/kpring/core/global/config/WebFluxStaticResourceConfig.kt
  core/src/main/kotlin/kpring/core/global/config/WebMvcStaticResourceConfig.kt
  server/src/main/kotlin/kpring/server/adapter/output/mongo/GetServerProfileMongoImpl.kt
  server/src/test/kotlin/kpring/server/adapter/input/rest/RestApiServerControllerTest.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBodyBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocMultipartFieldBuilder.kt
  test/src/main/kotlin/kpring/test/restdoc/json/JsonDataType.kt
  user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
  user/src/test/kotlin/kpring/user/controller/UserControllerTest.kt
Labels: bug
